[package]
name = "proxy-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
pingora = {version="0.5.0", features = ["proxy", "lb", "rustls"]}
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.11"
async-trait="0.1"
